/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ApexChart {
    /**
    * ApexCharts options
    */
    'options': object;
  }
  interface ApexChartAttributes extends StencilHTMLAttributes {
    /**
    * ApexCharts options
    */
    'options'?: object;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ApexChart': Components.ApexChart;
  }

  interface StencilIntrinsicElements {
    'apex-chart': Components.ApexChartAttributes;
  }


  interface HTMLApexChartElement extends Components.ApexChart, HTMLStencilElement {}
  var HTMLApexChartElement: {
    prototype: HTMLApexChartElement;
    new (): HTMLApexChartElement;
  };

  interface HTMLElementTagNameMap {
    'apex-chart': HTMLApexChartElement
  }

  interface ElementTagNameMap {
    'apex-chart': HTMLApexChartElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
